#+TITLE: Monster Meld Design

* Questions
   + How do (your) Monsters heal themselves
     + Automatically overtime?
     + Manually?
   + Should we continue to use Player Controllers or use rigidbodies instead?

* Todo List

** Monster Elements

*** Types
    + Fire (Red)
    + Ice (Blue)
    + Grass (Green)
    + Electric (Yellow)

*** Abilities
    + Ice Freezing
    + Fire Burning
    + Electric Arcing
      + Shadow Shawman

*** Behaviours

** Monster Rank

*** Rank 1

*** Rank 2

*** Rank 3?

** Monster Behaviour

*** TODO Attack Behaviour
    1. Monsters find an enmy based on the 'priority matrix'
       1. If all enemies have attackers, it will start attacking the closest enemy.
    2. The monster attacks its enemy until one of them dies.
    3. If the monster survives, it finds the next available enemy (Based on the priority list) and repeats
    4. Starts following the player once there's no more enemies left in the enemy MonsterGroup.

*** Priority Matrix
    Questions the monster asks itself before deciding to attack an enemy.
    + Health
      + Does my enemy have low health?
      + Do 'I' have low health?
    + Distance
      + How far is my enemy.
      + What is my range? How far do I need to be from my enemy to attack?
      + What is my enemy's range?
      + Flee Mode
    + Type
      + What special moves does my enemy have? Should I care?
      + Is my special move the best course of action against this enemy?

*** Monster Group
    

** Close/Mid/Long Range attacking

** Player

** Wild Monsters

*** Leashing

* Pseudo Code

** Effects

*** Description
Effects are buffs/debuffs added to monsters to enhance or impare their abilities or damage them overtime, etc.
Examples would include:

+ Frozen
  + Monster cannot move or attack for the duration of the effect, and is frozen in place.
+ Burning
  + Monster continuously recieves damage for the duration of the effect
+ Stunned
  + Monster cannot move or attack for the duration of the effect.
+ Being Healed
  + Monster continuously recieves health for the duration of the effect

*** Behaviour

*** Code

#+BEGIN_SRC csharp

public delegate void StatusEffectDelegate(StatusEffect effect);

public class StatusEffect : Monobehaviour {


    private float lifetime; // lifetime of the effect
    private float startTime;

    private float lastEffectTime; // The last time 'EffectBehaviour' was called
    private float effectDelay; // how often 'EffectBehaviour' is called

    private Monster targetMonster; // The monster that this effect is targeting
    

    public event StatusEffectDelegate OnEnd; // Invoked when the lifetime has ended


    void Start(){
	startTime = Time.time;
    }


    void Update(){
	if(Time.time >= startTime + lifeTime){
	    EndEffect();
	}
    }

    /// <summary>
    ///   what happens when the effect 'dies'
    /// </summary>
    protected virtual void EndEffect(){
	OnEnd(this);
    }

    /// <summary>
    ///   The behaviour of the effect. What does the effect do?
    /// </summary>
    protected virtual void EffectBehaviour(){
	//eg: Fire damage
	// Damage targetMonster 5 Hit Points 
    }
    

}

#+END_SRC

* Bugs
  + Problem when [[file:TestMonsterMeld/Assets/Scripts/MonsterGroup.cs][MonsterGroup]] sends monster to attack after attacking already.
    + [[file:TestMonsterMeld/Assets/Scripts/Monster.cs::316][Error Location]]
* Sources and References:
  Blockable text shader for Text Mesh: [[http://wiki.unity3d.com/index.php?title=3DText][Link To Source]] [[file:TestMonsterMeld/Assets/Materials/Shaders/TextShader.shader][File using source]]
  Text Shader Background: [[https://answers.unity.com/questions/385447/text-mesh-with-background.html][Link To Source]] [[file:TestMonsterMeld/Assets/Materials/Shaders/TextShader.shader][File using source]]
